language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install ".[test]" .
# command to run tests
script:
  coverage run -m unittest discover
after_success:
  bash <(curl -s https://codecov.io/bash)