language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install ".[test]" .
# command to run tests
script:
  - pytest --cov-report term --cov=investpy tests/
after_success:
  - codecov